name: work_flutter
description: "rvierpod_cart_app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # 더 넓은 버전 범위를 허용하여 다른 SDK와 호환 되도록 한다
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed: ^2.5.8
  freezed_annotation: ^2.4.1
  build_runner: ^2.4.15
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
