name: work_flutter
description: "rvierpod_cart_app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  freezed: ^3.0.6
  freezed_annotation: ^3.1.0
  build_runner: ^2.4.15
#  riverpod: ^2.6.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
